version: '2'
services:
  es1:
    image: elasticsearch:2.3.4
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - es2
      - es3
    command: "elasticsearch -Dcluster.name='elk-training'  -Dnode.name=es1 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin=* -Ddiscovery.zen.ping.unicast.hosts=es2,es3"
  es2:
    image: elasticsearch:2.3.4
    ports:
      - "9200"
      - "9300"
    links:
      - es3
    command: "elasticsearch -Dcluster.name='elk-training' -Dnode.name=es2 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin=* -Ddiscovery.zen.ping.unicast.hosts=es1,es3"
  es3:
    image: elasticsearch:2.3.4
    ports:
      - "9200"
      - "9300"
    command: "elasticsearch -Dcluster.name='elk-training' -Dnode.name=es3 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin=* -Ddiscovery.zen.ping.unicast.hosts=es1,es2" 
