version: '2'
services:
  es1:
    image: elasticsearch:5.1.2
    ports:
      - "9200:9200"
      - "9300:9300"
    links:
      - es2
      - es3
    command: "elasticsearch -Ecluster.name='elk-training'  -Enode.name=es1 -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=* -Ediscovery.zen.ping.unicast.hosts=es2,es3"
  es2:
    image: elasticsearch:5.1.2
    ports:
      - "9200"
      - "9300"
    links:
      - es3
    command: "elasticsearch -Ecluster.name='elk-training' -Enode.name=es2 -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=* -Ediscovery.zen.ping.unicast.hosts=es1,es3"
  es3:
    image: elasticsearch:5.1.2
    ports:
      - "9200"
      - "9300"
    command: "elasticsearch -Ecluster.name='elk-training' -Enode.name=es3 -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=* -Ediscovery.zen.ping.unicast.hosts=es1,es2" 
